/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IUser,
} from './components/my-component/mv-label';

export namespace Components {
  interface MvLabel {
    'status': string;
    'title': string;
    'user': IUser;
    'userId': number;
  }
}

declare global {


  interface HTMLMvLabelElement extends Components.MvLabel, HTMLStencilElement {}
  var HTMLMvLabelElement: {
    prototype: HTMLMvLabelElement;
    new (): HTMLMvLabelElement;
  };
  interface HTMLElementTagNameMap {
    'mv-label': HTMLMvLabelElement;
  }
}

declare namespace LocalJSX {
  interface MvLabel extends JSXBase.HTMLAttributes<HTMLMvLabelElement> {
    'status'?: string;
    'title'?: string;
    'user'?: IUser;
    'userId'?: number;
  }

  interface IntrinsicElements {
    'mv-label': MvLabel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


